const mongoose = require('mongoose');

const resumeSchema = new mongoose.Schema({
  originalFilename: {
    type: String,
    required: true,
  },
  extractedText: {
    type: String,
    required: true,
  },
  fileHash: {
    type: String,
    required: true,
    unique: true,
  },
  parsedData: {
    name: String,
    email: String,
    phone: String,
    skills: [String],
    projects: [String],
    education: [String],
    experience: [String],
    certifications: [String],
    languages: [String],
    links: {
      github: String,
      linkedin: String,
      portfolio: String,
    },
  },
  analysis: {
    resumeScore: Number,
    atsScore: Number,
    formattingScore: Number,
    grammarScore: Number,
    projectScore: Number,
    experienceScore: Number,
    educationScore: Number,
    skillScore: Number,
    keywordScore: Number,
    jobMatchScore: Number,
    recruiterConfidence: String,
    interviewReadiness: String,
    resumeGrade: String,
    hiringProbability: Number,
    strengths: [String],
    weaknesses: [String],
    criticalGaps: [String],
    priorityRecommendations: [String],
    estimatedAtsImprovement: Number,
    suggestedJobTitles: [String],
    suggestedCompanyTypes: [String],
    recommendedSalaryRange: String,
    industryFit: String,
    overallVerdict: String,
    improvementSuggestions: [String],
    recruiterFeedback: {
      estimatedStrength: String,
      likelyImpression: String,
      shortlistDecision: String,
      shortlistReason: String,
      top5Strengths: [String],
      top5Weaknesses: [String],
      criticalImprovementSection: String,
      criticalImprovementReason: String,
      suitableCompanyTypes: [String],
      atsCompatibility: String,
      suggestedNextActions: [String]
    },
  },
  atsResult: {
    score: Number,
    suggestions: [String],
    issues: [String],
    missingSections: [String],
    contactInfo: { present: Boolean, score: Number },
    summary: { present: Boolean, score: Number },
    skills: { present: Boolean, score: Number },
    projects: { present: Boolean, score: Number, strength: String, recommendations: [String] },
    experience: { present: Boolean, score: Number },
    education: { present: Boolean, score: Number },
    formatting: { score: Number },
    actionVerbs: { score: Number },
    achievements: { score: Number },
    keywordDensity: { score: Number },
    resumeLength: { score: Number },
    sectionOrder: { score: Number },
  },
  jobMatch: {
    jobDescription: String,
    matchPercentage: Number,
    roleAlignment: Number,
    experienceMatch: Number,
    skillMatch: Number,
    keywordMatch: Number,
    matchingSkills: [String],
    missingKeywords: [String],
    missingSkills: [String],
    recommendedResumeChanges: [String],
    suggestedResumeSummary: String,
    suitableRoles: [String],
    experienceGap: String,
    educationGap: String,
    suggestions: [String]
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

module.exports = mongoose.model('Resume', resumeSchema);
